= Generics

== Introdution

=== Purpose

Introduced in Java 1.5. Before collections consisted of Objects.
Those resulted in Casts when retrieving. This could cause ClassCastException at Runtime
To avoid this compile-time type checking was added with Generics.

[source,java]

List list = new ArrayList(); // Java 1.5
list.add("abc");
list.add(new Integer(5))
for(Object obj : list) { String str=(String) obj; }
List<String> list = new ArrayList<String>(); // Java 1.7+
list1.add("abc");
for(String str : list1){ }

If the Generics Type is omitted,
Java will use Object and warn about "raw usage".


=== Inheritance (Recap)
All parametrized classes still inherit from Object.
Thus they can't be cast from one to another.
[source,java]
String str = "";
Object obj = new Object();
List<String> strList = new ArrayList<>();
List<Object> objList = new ArrayList<>();
//
obj = str;           // OK
str = (String) obj;  // OK (here obj is a String instance with a Object reference,
// if obj were an Object instance, then ClassCastException at runtime.
objList = strList    // C-Error
obj = strList        // OK
//
interface MyList<E,T> extends List<E>{} // Example of what can be done with generics.



== Summary

=== Abbreviations
** Generic Type : `T`
** Generic Type Wildcard : `?`

====  T <> ?

[options=header]
|===
||`T` | `?`
|Can be used with... | class, method, field, param, local var | field, param, local var
|Needs to be declared in enclosing class or method? | YES +
Syntax in class: +
`Class<T>{}` +
Syntax in method: +
`<T> return-type method(){}` | NO
|===




==== Bounds
* unbounded (`<T>`)
* upper bound (`<T1 extends T2>`) may be used with/without a wildcard.
* lower bound (`<T1 super T2>`) may only be used with wildcard


==== Cheatsheet (Complete)

[options=header, cols="7,5,5,5"]
|===
| Declaration Scenarios                   | unbounded | upper bound | lower bound
| Class with `<T>`   2+^| YES            |
| Class with `<?>`   3+|
| Method with `<T>`  2+^| YES          |
| Method with `<?>`  3+|
| Field with `<T>`   | If T declared in Class. 2+|
| Field with `<?>`   3+^| YES
| Parameter (or local var) with <T> | If T declared in Method (or Class). 2+|
| Parameter (or local var) with `<?>`   3+^| YES
|===

[options=header, cols="7,5"]
|===
| Type Scenarios |
| Method with return type `T` | If T declared in Class.
| Method with return type `?` |
| Field of type `T`   | If T declared in Class.
| Field of type `?`   |
| Parameter of type `T`   | If T declared in Method (or Class).
| Parameter of type `?`   |
| Local var of type `T`   | If T declared in Method (or Class).
| Local var of type `?`   | Use `var` instead.
|===

==== Naming

|===
| E |Element of Collection
| K |Key of Map
| N |Number
| T |Type
| V |Value of Map
| S , U | Other
|===


==== Other
* Overriding with Generics see Methods.adoc


==== What can't be done with generics:

Call the constructor. new T() is not allowed because at runtime it would be new
Object().
Create an array of that static type. This one is the most annoying, but it makes sense
because you’d be creating an array of Objects.
Call instanceof. This is not allowed because at runtime List<Integer> and
List<String> look the same to Java thanks to type erasure.
Use a primitive type as a generic type parameter. This isn’t a big deal because you
can use the wrapper class instead. If you want a type of int, just use Integer.
Create a static variable as a generic type parameter. This is not allowed because the
type is linked to the instance of the class.

{empty} +

==== Bound Wildcard Collections
* Java is very conservative in what it allows to be added to "wildcarded-collections".
* Example:

[cols="2,6"]
|===
| What it is | a List of type Parent
| What it says | a List of type Child or one of it's superclasses.
| What it means | a List that is guaranteed to hold Child or any of it's subclasses.
| Why? | if list was of type Child and one added a Parent -> ClassCastException
|===


[source,java]
List<? super Child> list2 = new ArrayList<Parent>();
list2.add(new Object());  // C-Error
list2.add(new Parent());  // C-Error
list2.add(new Child());
list2.add(new SubChild());

* For the same reason unbounded and upper bounds wildcards make the collection effectively immutable.

[cols="2,6"]
|===
| What it is | A List of type Child
| What it says | A List of type Parent or one of it's subclasses.
| What it means | The List is not guaranteed to hold known classes, as the inheritance tree might be extended. +
If we add any of the known classes, a `ClassCastException` might happen.
|===

[source,java]
List<? Extends Parent> list2 = new ArrayList<Child>();
list2.add(new Object());  // C-Error
list2.add(new Parent());  // C-Error
list2.add(new Child());   // C-Error
list2.add(new SubChild());