@startuml

title __POLYMORPHISM's Class Diagram__\n

  namespace  {
    namespace lasses {
      namespace polymorphism {
        class classes.polymorphism.BCA {
        }
      }
    }
  }
  

  namespace  {
    namespace lasses {
      namespace polymorphism {
        class classes.polymorphism.BCB {
        }
      }
    }
  }
  

  namespace  {
    namespace lasses {
      namespace polymorphism {
        interface classes.polymorphism.BCInterface {
        }
      }
    }
  }
  

  namespace  {
    namespace lasses {
      namespace polymorphism {
        class classes.polymorphism.BadCasting {
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace lasses {
      namespace polymorphism {
        class classes.polymorphism.Child {
            + privateInParent : int
            + publicInt : int
            + weird : int
            {static} ~ i : int
            - foo : int
            - privateInt : int
            {static} + main()
            + pubicMethod()
            {static} ~ finalMethod()
            - privateMethod()
        }
      }
    }
  }
  

  namespace  {
    namespace lasses {
      namespace polymorphism {
        class classes.polymorphism.Parent {
            + publicInt : int
            ~ foo : int
            - privateInt : int
            - wierd : int
            + pubicMethod()
            ~ finalMethod()
            - privateMethod()
        }
      }
    }
  }
  

  namespace  {
    namespace lasses {
      namespace polymorphism {
        class classes.polymorphism.Polymorphism {
            {static} ~ b : boolean
            {static} ~ i : int
            {static} + main()
            {static} ~ casting()
            {static} ~ instanceOf()
        }
      }
    }
  }
  

  classes.polymorphism.BCA .up.|> classes.polymorphism.BCInterface
  classes.polymorphism.BCB .up.|> classes.polymorphism.BCInterface
  classes.polymorphism.Child -up-|> classes.polymorphism.Parent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
