| Annotation | Description |
---|---
| @Configuration |

*
* @Component : candidate for auto-detection
    * @Controller
    * @Repository
    * @Service
* @Conditional
*
* @ControllerAdvice
* @Entity JPA annotation to make this object ready for storage in a JPA-based data store.
* @InitBinder
* @Inject


* @ModelAttribute
* @Named
* @PathVariable
*
*
* @Profile

* @Qualifier wire only one bean out of several candidates
* @Query
* @RequestMapping
* @RequestParam
* @RequestHeader
* @Required
* @Resource
*
* @SessionAttributes
*

{empty} +

== A
==== @Autowired
auto. detect bean dependencies, instead of using XML-config. +
Spring @Autowired annotation is used for automatic injection of beans. +
Spring @Qualifier annotation is used in conjunction with Autowired to avoid confusion when we have two of more bean configured for same type.



{empty} +

== B
==== @Bean
Indicates that a method produces a bean to be managed by the Spring container. +
This is one of the most used and important spring annotation.+
@Bean annotation also can be used with parameters like name, initMethod and destroyMethod.

* name – allows you give name for bean
* initMethod – allows you to choose method which will be invoked on context register
* destroyMethod – allows you to choose method which will be invoked on context shutdown


{empty} +

== C
==== @Configuration
Used to indicate that a class declares one or more @Bean methods. +
These classes are processed by the Spring container to generate bean definitions and service requests for those beans at runtime.

==== @Component
Indicates that an annotated class is a “component”. +
Such classes are considered as candidates for auto-detection when using annotation-based configuration and classpath scanning.

* Generalization of `@Service` , `@Repository` .

==== @ComponentScan
Configures component scanning directives for use with @Configuration classes. +
Here we can specify the base packages to scan for spring components.

==== @Controller
Spring MVC

{empty} +

== E
==== @EnableAutoConfiguration
Spring Boot


{empty} +

== P
==== @PathVariable
Spring MVC

==== @PostConstruct
alternative way for bean initMethod +
It can be used when the bean class is defined by us


==== @PreDestroy
alternative way for bean destroyMethod +
It can be used when the bean class is defined by us

==== @PropertySource
provides a simple declarative mechanism for adding a property source to Spring’s Environment. +
There is a similar annotation for adding an array of property source files i.e `@PropertySources`.



{empty} +

== R
==== @Repository
Indicates that an annotated class is a “Repository”. +

* specialization of `@Component`
* advisable to use with DAO classes.

==== @RestController
indicates that the data returned by each method will be written straight into the response body instead of rendering a template.

==== @RequestMapping
Spring MVC


{empty} +

== S
==== @Service
Indicates that an annotated class is a “Service”. +

* specialization of `@Component`,
* allowing for implementation classes to be autodetected through classpath scanning.

==== @SpringBootApplication
@Configuration, @EnableAutoConfiguration, and @ComponentScan


{empty} +

== T
==== @Transactional
is the spring declarative transaction management annotation, read more at Spring MVC Hibernate.


{empty} +

== V
==== @Value
goes to search vor value in `src/main/application.properties`
