== Concepts

=== IoCC (IoC Container)
* IoCC
** is responsible for injecting the dependency.
** is responsible to instantiate, configure and assemble the objects.
*** to instantiate the application class
*** to configure the object
*** to assemble the dependencies between the objects
* We provide metadata to the IoC container by XML or Annotations.
* There are two types of IoCC
** `org.springframework.beans.factory.BeanFactory`
** `org.springframework.context.ApplicationContext`
*** `ApplicationContext extends BeanFactory`


=== DI (Dependency Injection)
* See `design/decoupling/levels/Levels.adoc` for an overview.
* DI is the opposite of _dependency lookup_
** resource is retrieved after demand
** `A obj = new AImpl();`
** `A obj = A.getA(); // using factory`
** tight coupling
** complicates testing
* Spring supports
** Constructor injection
** Method injection (by setter)

{empty} +


#### HAL : Hypertext Application Language
HAL is a simple format that gives a consistent and easy way to hyperlink between resources in your API.

Adopting HAL will make your API explorable, and its documentation easily discoverable from within the API itself.
In short, it will make your API easier to work with and therefore more attractive to client developers.


APIs that adopt HAL can be easily served and consumed using open source libraries available for most major programming languages.
It's also simple enough that you can just deal with it as you would any other JSON.

http://stateless.co/hal_specification.html

#### CORS : cross-origin resource sharing
s a mechanism that allows restricted resources on a web page
to be requested from another domain outside the domain from which the first resource was served
