@startuml

title __COLLECTIONS's Class Diagram__\n

  namespace collections {
    class collections.Array {
        {static} ~ a1D : int[]
        {static} ~ a2D : int[][]
        {static} ~ a3D : int[][][]
        {static} ~ b : boolean
        {static} ~ i : int
        {static} + compareArrays()
        {static} + main()
        {static} ~ legalDeclarations()
        {static} ~ methods()
        {static} ~ special()
    }
  }
  

  namespace collections {
    interface collections.CollectionCopy {
        {abstract} + add()
        {abstract} + clear()
        {abstract} + isEmpty()
        {abstract} + remove​()
        {abstract} + size()
    }
  }
  

  namespace collections {
    class collections.Conversions {
        {static} ~ b : boolean
        {static} ~ capturingArray : Integer[]
        {static} ~ i : int
        {static} ~ integerArray : Integer[]
        {static} ~ integerList : List<Integer>
        {static} ~ objArray : Object[]
        {static} + main()
        {static} ~ arrayToList()
        {static} ~ listToArray()
    }
  }
  

  namespace collections {
    interface collections.ListCopy {
        {abstract} + add​()
        {abstract} + remove​()
        {abstract} + set​()
    }
  }
  

  namespace collections {
    class collections.Lists {
        {static} ~ b : boolean
        {static} ~ i : int
        {static} ~ integerArray : Integer[]
        {static} ~ integerList : List<Integer>
        {static} ~ objArray : Object[]
        {static} ~ outputArray : Integer[]
        {static} + main()
        {static} ~ special()
    }
  }
  

  namespace collections {
    interface collections.MapCopy {
        {abstract} + isEmpty()
        {abstract} + size()
    }
  }
  

  namespace collections {
    class collections.Maps {
        {static} ~ b : boolean
        {static} ~ hashMap : Map<Integer, String>
        {static} ~ s : String
        {static} + main()
        {static} ~ methods()
    }
  }
  

  namespace collections {
    class collections.Sets {
        {static} ~ b : boolean
        {static} ~ hashSet : Set<Character>
        {static} + main()
        {static} ~ methods()
    }
  }
  

  namespace collections {
    interface collections.StackCopy {
        {abstract} + empty()
        {abstract} + peek()
        {abstract} + pop()
    }
  }
  

  namespace collections {
    class collections.ToDo {
        {static} + editList()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
