@startuml

title __PRIMITIVES's Class Diagram__\n

  namespace  {
    namespace rimitives {
      class primitives.Boolean {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace rimitives {
      class primitives.Chars {
          {static} + main()
          {static} ~ promotion()
      }
    }
  }
  

  namespace  {
    namespace rimitives {
      class primitives.Examples {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace rimitives {
      class primitives.FloatingPoint {
          {static} ~ d : double
          {static} ~ f : float
          ~ f1 : float
          ~ f3 : float
          ~ f4 : float
          {static} + main()
          {static} ~ doubleDemo()
          {static} ~ floatDemo()
      }
    }
  }
  

  namespace  {
    namespace rimitives {
      class primitives.Integers {
          {static} ~ aLong : Long
          {static} ~ b : boolean
          ~ binary : int
          ~ fine : int
          ~ hexadecimal : int
          {static} ~ i : int
          {static} ~ integer : Integer
          {static} ~ integer1 : Integer
          {static} ~ integer2 : Integer
          {static} ~ l : long
          ~ octal : int
          {static} + main()
          {static} ~ basicOperators()
          {static} ~ comparison()
          {static} ~ methods()
          {static} - aboutLong()
      }
    }
  }
  

  namespace  {
    namespace rimitives {
      class primitives.Primitives {
          {static} ~ c : char
          {static} ~ i : int
          {static} ~ l : long
          {static} + main()
          ~ charDemo()
          ~ intDemo()
      }
    }
  }
  

  namespace  {
    namespace rimitives {
      class primitives.Short {
          ~ foo : short
          {static} + main()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
