= ðŸ‹ WildFly
:stylesheet: ../../shared/adoc-styles.css


[source]
docker exec -it -u root $CONTAINER_NAME sh
./bin/jboss-cli.sh
connect

[source]
/subsystem=elytron/jaas-realm=jaasRealmExample:add( entry=Entry1)
/subsystem=elytron/jaas-realm=jaasRealmExample:add(entry=Entry2, path=/opt/jboss/wildfly/standalone/configuration/jaas.conf)
/subsystem=elytron/jaas-realm=jaasRealmExample:add(entry=Entry2, path=/path/to/JAAS-config-file.conf, module=moduleContainingCustomImpls, callback-handler=loginmodules.CustomCallbackHandler)

=== Workflow to get CLI >>
* run container
* run CLI command
* copy change to standalone

{empty} +

=== Commands vs Results

[source,xml]
/subsystem=undertow/application-security-domain=MyAppSecurity:add(security-domain=ApplicationDomain)
//
<application-security-domain name="MyAppSecurity" security-domain="ApplicationDomain"/>


[source,xml]
./subsystem=elytron/jaspi-configuration=simple-configuration:add(layer=HttpServlet, application-context="default-host /webctx", \
        description="Elytron Test Configuration", \
        server-auth-modules=[{class-name=org.wildfly.security.examples.jaspi.SimpleServerAuthModule, module=org.wildfly.security.examples.jaspi, flag=OPTIONAL, options={a=b, c=d}}, \
            {class-name=org.wildfly.security.examples.jaspi.SecondServerAuthModule, module=org.wildfly.security.examples.jaspi}])
<jaspi>
				<jaspi-configuration name="simple-configuration"
									 layer="HttpServlet"
									 application-context="default-host /webctx"
									 description="Elytron Test Configuration">
					<server-auth-modules>
						<server-auth-module class-name="org.wildfly.security.examples.jaspi.SimpleServerAuthModule"
											module="org.wildfly.security.examples.jaspi"
											flag="OPTIONAL">
							<options>
								<property name="a" value="b"/>
								<property name="c" value="d"/>
							</options>
						</server-auth-module>
						<server-auth-module class-name="org.wildfly.security.examples.jaspi.SecondServerAuthModule"
											module="org.wildfly.security.examples.jaspi"/>
					</server-auth-modules>
				</jaspi-configuration>
			</jaspi>


https://docs.wildfly.org/25/WildFly_Elytron_Security.html
